unit uColorCallidus;

interface

uses
  Graphics;

const
  COLORWINDOW_WORKING = $E0FFFF;
  COLORWINDOW_ERROR = $E0E0FF;
  COLORWINDOW_SUCCESS = $E0FFE0;
  COLORWINDOW_EXCLUDED = $D0F0F0;
  COLORWINDOW_WHITE = clWhite;
  COLORWINDOW_DISABLED = $F0F0F0;

  COLORDANGER = clOlive;
  COLORERROR = clRed;
  COLORSUCCESS = clGreen;
  COLORATR = clBlue;
  COLORSTATUS = clBlack;
  COLORERRORDETAIL = clMaroon;
  COLORSPECIAL = clFuchsia;
  COLORETHERNET = clMoneyGreen;
  COLORDEBUG = clGray;
  COLORFATIGUANTE = $D070FF;
  COLORDANGERLEGER = $40C0C0;
  COLORPALE = clGray;
  COLOR_DEBUG_SECTIONTITLE = $666666;
  COLOR_DEBUG_EXCEPTION = $888888;
  COLOR_DEBUG_ITEMST = $AAAAAA;
  COLOR_DEBUG_ENDSECTIONTITLE = $CCCCCC;
  COLORERRORCONCLUSION = $1010FF;
  COLORINFO1 = clBlue;
  COLORERASE = clMaroon;
  COLORDECEPTION = clMaroon;
  COLOR_SENDTOSPHINX = clTeal;
  COLORTX = COLOR_SENDTOSPHINX;
  COLOR_ANSWERSPHINX = clSilver;
  COLORRX = COLORDECEPTION;
  COLOR_BEFOREENCRYPTION = clNavy;
  COLOR_AFTERENCRYPTION = clBlue;
  COLOR_AFTERDECRYPTION = clGray;
  COLOR_REFORMATTEDFORCARD = clMaroon;
  COLOR_OUVERTUREFERMETUREFICHIER = clMaroon;
  COLOR_VERIFICATION = clGray - $101010;
  COLOR_ANSWERCARD = clFuchsia;
  COLOR_SENDTOCARD = clPurple;
  COLOR_NEEDTOPROG = clPurple;
  COLORERROR2 = $12345678;
  COLORBLUBERI = $C97A00;
  clBleuPale = $00000010;
  COLORSECTIONTITLE = $1234567;
  COLORSUBSECTIONTITLE = $1234568;
  COLORSUBSUBTEST = $1234569;

  COLORBACKGROUND_WORKING = $E0FFFF;
  COLORBACKGROUND_SUCCESS = $E0FFE0;
  COLORBACKGROUND_ERROR = $E0E0FF;

  LOG_COULEUR = TRUE;
  LOG_BLACKANDWHITE = FALSE;

implementation

end.
